### ISSUE TITLE
Error in rendering internal://router.go.tmpl

### ISSUE THREAD

**Issue by kitesoft** [smallnest/gen#113]
Error in rendering internal://router.go.tmpl: template: router.go.tmpl:347:22: executing "router.go.tmpl" at <.modelPackageName>: can't evaluate field modelPackageName in type *dbmeta.ModelInfo

how to fix this error?

**Comment by dwgeneral** [comment]
I have a same issue

**Comment by ammend** [comment]
me too.

**Comment by ammend** [comment]
> Error in rendering internal://router.go.tmpl: template: router.go.tmpl:347:22: executing "router.go.tmpl" at <.modelPackageName>: can't evaluate field modelPackageName in type *dbmeta.ModelInfo
> 
> how to fix this error?

have u fixed this problem?

**Comment by ammend** [comment]
> I have a same issue

have u fixed this problem?

**Comment by ammend** [comment]
@alexj212 may u look at the issue. something wrong with running gen.

**Comment by alexj212** [comment]
Fixed in v0.9.20

**Comment by ammend** [comment]
> v0.9.20

many thanks.

**Comment by ammend** [comment]
> Fixed in v0.9.20

when I rm gen and install gen v0.9.20, go get log shows install v0.9.20, but gen --version is v0.9.18.
and the result is that 
Error in rendering internal://router.go.tmpl: template: router.go.tmpl:348:22: executing "router.go.tmpl" at <.modelPackageName>: can't evaluate field modelPackageName in type *dbmeta.ModelInfo
error not fixed yet.
@alexj212

**Comment by alexj212** [comment]
@ammend  sloppy mistake on my part - do a new install of v0.9.21
